# Generated by Django 4.1.7 on 2023-03-20 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 21), null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(blank=True, default=leads.models.Lead.get_default_category, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.category'),
        ),
    ]
