# Generated by Django 4.1.7 on 2023-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_campaign_start_date_alter_followup_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
