# Generated by Django 4.1.7 on 2023-03-31 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_followup_next_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('telecaller', 'Telecaller'), ('marketing_staff', 'Marketing Staff'), ('monitor', 'Monitor')], default='Tester', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 1), null=True),
        ),
    ]
