# Generated by Django 4.1.7 on 2023-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_agent_role_alter_followup_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('Telecaller', 'Telecaller'), ('Marketing Staff', 'Marketing Staff'), ('Monitor', 'Monitor')], max_length=20),
        ),
    ]
