# Generated by Django 4.1.7 on 2023-03-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_agent_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='agent',
        ),
        migrations.AddField(
            model_name='campaign',
            name='agent',
            field=models.ManyToManyField(blank=True, to='leads.agent'),
        ),
    ]
