# Generated by Django 4.1.7 on 2023-04-02 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_remove_campaign_agent_campaign_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 3), null=True),
        ),
    ]
