# Generated by Django 4.1.7 on 2023-04-03 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_followup_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 4), null=True),
        ),
    ]
