# Generated by Django 4.1.7 on 2023-04-07 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_followup_next_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadformsubmission',
            name='date_submitted',
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 8), null=True),
        ),
        migrations.AlterField(
            model_name='leadformsubmission',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='leadformsubmission',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leadformsubmission',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
