# Generated by Django 4.1.7 on 2023-04-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_remove_leadformsubmission_date_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadformsubmission',
            name='job_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadformsubmission',
            name='q1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
