# Generated by Django 4.1.7 on 2023-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_leadformsubmission_job_title_leadformsubmission_q1'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadformsubmission',
            name='form_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
