# Generated by Django 4.1.7 on 2023-04-08 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_leadformsubmission_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='a1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.TextField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='job_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='q1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 9), null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
