# Generated by Django 4.1.7 on 2023-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_campaign_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(default='Manual', max_length=20),
        ),
    ]
