# Generated by Django 4.1.7 on 2023-04-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_rename_form_id_campaign_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
