# Generated by Django 4.1.7 on 2023-04-20 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_lead_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('Telecaller', 'Telecaller'), ('Marketing Staff', 'Marketing Staff'), ('Monitor', 'Monitor')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 21), null=True),
        ),
    ]
