# Generated by Django 4.1.7 on 2023-05-02 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_alter_followup_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 3), null=True),
        ),
    ]
