# Generated by Django 4.1.7 on 2023-05-12 02:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_alter_followup_next_date_alter_lead_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 13), null=True),
        ),
    ]
