# Generated by Django 4.1.7 on 2023-05-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_alter_campaign_options_followup_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='agent',
            field=models.ManyToManyField(blank=True, null=True, to='leads.agent'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
