# Generated by Django 4.1.7 on 2023-05-16 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_alter_campaign_agent_alter_campaign_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='agent',
            field=models.ManyToManyField(blank=True, to='leads.agent'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 17), null=True),
        ),
    ]
