# Generated by Django 4.1.7 on 2023-05-21 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_alter_campaign_agent_alter_campaign_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 22), null=True),
        ),
    ]
