# Generated by Django 4.1.7 on 2023-05-23 01:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_lead_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='campaign',
        ),
        migrations.AddField(
            model_name='notification',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 24), null=True),
        ),
    ]
