# Generated by Django 4.1.7 on 2023-05-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_alter_notification_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='lead',
        ),
    ]
