# Generated by Django 4.1.7 on 2023-05-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_remove_notification_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
    ]
