# Generated by Django 4.1.7 on 2023-05-27 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0037_notification_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 28), null=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
