# Generated by Django 4.1.7 on 2023-05-31 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0038_alter_followup_next_date_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 1), null=True),
        ),
    ]
